prompt              : "> "
compiler            : "gcc"
compiler_version    : "--version"
compiler_args       : "-x c --std=gnu11 -o $outfile - $include_dirs $lib_dirs $libs"
history_file        : "$HOME/.igcc_history"
history_size        : "1000"
include_dir_cmd     : "-I$cmd"
lib_dir_cmd         : "-L$cmd"
lib_cmd             : "-l$cmd"
version             : "0.690"
